swagger: "2.0"
info:
  title: Order Ticket API
  description: API for managing order tickets
  version: "1.0.0"
tags:
  - name: Order Tickets
    description: Order management routes for tickets

paths:
  /api/order-ticket:
    get:
      summary: Get all order tickets
      tags:
        - Order Tickets
      responses:
        200:
          description: A list of all order tickets
    post:
      summary: Create a new order ticket
      tags:
        - Order Tickets
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              eventId:
                type: string
                description: The event ID for the ticket order
                example: "12345"
              userId:
                type: string
                description: The user ID for the ticket order
                example: "67890"
              quantity:
                type: integer
                description: The number of tickets to be ordered
                example: 3
      responses:
        201:
          description: Order ticket created successfully
        400:
          description: Invalid input

  /api/order-ticket/{id}:
    get:
      summary: Get order ticket by ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket
          type: string
      responses:
        200:
          description: The order ticket record
        404:
          description: Order ticket not found
    put:
      summary: Update an existing order ticket
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to update
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              quantity:
                type: integer
                description: The updated number of tickets
                example: 4
      responses:
        200:
          description: Order ticket updated successfully
        400:
          description: Invalid input
        404:
          description: Order ticket not found
    delete:
      summary: Delete an order ticket by ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to delete
          type: string
      responses:
        200:
          description: Order ticket deleted successfully
        404:
          description: Order ticket not found

  /api/order-ticket/{id}/invoice:
    get:
      summary: Get order ticket by invoice ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to retrieve by invoice
          type: string
      responses:
        200:
          description: Order ticket retrieved successfully
        404:
          description: Order ticket not found
