swagger: "2.0"
info:
  title: Order Ticket API
  description: API for managing order tickets
  version: "1.0.0"
tags:
  - name: Order Tickets
    description: Order management routes for tickets

paths:
  /api/ticket/order:
    get:
      summary: Get all order tickets
      tags:
        - Order Tickets
      responses:
        200:
          description: A list of all order tickets
    post:
      summary: Create a new order ticket
      tags:
        - Order Tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The user ID for the ticket order
                  example: "550e8400-e29b-41d4-a716-446655440000"
                ticketId:
                  type: string
                  description: The ticket ID for the order
                  example: "123e4567-e89b-12d3-a456-426614174000"
                eventId:
                  type: string
                  description: The event ID for the ticket order
                  example: "123e4567-e89b-12d3-a456-426614174000"
                quantity:
                  type: integer
                  description: The number of tickets to be ordered
                  example: 3
                totalPrice:
                  type: number
                  format: decimal
                  description: The total price for the ticket order
                  example: 150.75
                paymentStatus:
                  type: string
                  description: The payment status of the order
                  enum:
                    - PENDING
                    - PAID
                    - FAILED
                    - REFUNDED
                  example: "PAID"
                orderStatus:
                  type: string
                  description: The order status
                  enum:
                    - NEW
                    - CONFIRMED
                    - CANCELLED
                  example: "NEW"
      responses:
        201:
          description: Order ticket created successfully
        400:
          description: Invalid input

  /api/ticket/order/{id}:
    get:
      summary: Get order ticket by ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket
          type: string
      responses:
        200:
          description: The order ticket record
        404:
          description: Order ticket not found
    put:
      summary: Update an existing order ticket
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to update
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: The number of tickets to be ordered
                  example: 3
                totalPrice:
                  type: number
                  format: decimal
                  description: The total price for the ticket order
                  example: 150.75
                paymentStatus:
                  type: string
                  description: The payment status of the order
                  enum:
                    - PENDING
                    - PAID
                    - FAILED
                    - REFUNDED
                  example: "PAID"
                orderStatus:
                  type: string
                  description: The order status
                  enum:
                    - NEW
                    - CONFIRMED
                    - CANCELLED
                  example: "NEW"
      responses:
        200:
          description: Order ticket updated successfully
        400:
          description: Invalid input
        404:
          description: Order ticket not found
    delete:
      summary: Delete an order ticket by ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to delete
          type: string
      responses:
        200:
          description: Order ticket deleted successfully
        404:
          description: Order ticket not found

  /api/ticket/order/{id}/invoice:
    get:
      summary: Get order ticket by invoice ID
      tags:
        - Order Tickets
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the order ticket to retrieve by invoice
          type: string
      responses:
        200:
          description: Order ticket retrieved successfully
        404:
          description: Order ticket not found
