swagger: "2.0"
info:
  title: Organization API
  description: API documentation for managing organizations and their events
  version: "1.0.0"
tags:
  - name: Organizations
    description: Operations related to organizations and their events
paths:
  /api/organizer/{id}/events:
    get:
      summary: Get events managed by a specific organizer
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: List of events for the organizer
  /api/organizer/{id}/dashboard:
    get:
      summary: Get organizer's dashboard data
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: Dashboard data of the organizer
  /api/organizer/{id}/event-status-summary:
    get:
      summary: Get summary of the event status for a specific organizer
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: Event status summary for the organizer
  /api/organizer/{id}/venues:
    get:
      summary: Get venues associated with a specific organizer
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: List of venues for the organizer
  /api/organizer/{id}/top-event:
    get:
      summary: Get the top event for a specific organizer
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: The top event of the organizer
  /api/organizer/{id}/all-tickets:
    get:
      summary: Get all tickets sold for events organized by a specific organizer
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organizer
          schema:
            type: string
      responses:
        200:
          description: List of all tickets sold for the organizer's events
  /api/organizer:
    get:
      summary: Get all organizations
      tags:
        - Organizations
      responses:
        200:
          description: A list of all organizations
    post:
      summary: Create a new organization
      tags:
        - Organizations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: uuid
                  description: The ID of the user creating the organization
                  example: "123e4567-e89b-12d3-a456-426614174000"
                organizationName:
                  type: string
                  description: The name of the organization
                  example: "Event Organizer Inc."
                contactName:
                  type: string
                  description: The name of the contact person
                  example: "John Doe"
                contactPhone:
                  type: string
                  description: The phone number of the contact person
                  example: "+1234567890"
                contactEmail:
                  type: string
                  format: email
                  description: The email address of the contact person
                  example: "contact@example.com"
      responses:
        201:
          description: Organization created successfully
        400:
          description: Invalid input
  /api/organizer/{id}:
    get:
      summary: Get organization by ID
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organization
          schema:
            type: string
      responses:
        200:
          description: Organization details
        404:
          description: Organization not found
    put:
      summary: Update an organization by ID
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organization to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organizationName:
                  type: string
                  description: The name of the organization
                  example: "Event Organizer Inc."
                contactName:
                  type: string
                  description: The name of the contact person
                  example: "John Doe"
                contactPhone:
                  type: string
                  description: The phone number of the contact person
                  example: "+1234567890"
                contactEmail:
                  type: string
                  format: email
                  description: The email address of the contact person
                  example: "contact@example.com"
      responses:
        200:
          description: Organization updated successfully
        400:
          description: Invalid input
        404:
          description: Organization not found
    delete:
      summary: Delete an organization by ID
      tags:
        - Organizations
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the organization to delete
          schema:
            type: string
      responses:
        200:
          description: Organization deleted successfully
        404:
          description: Organization not found
