swagger: "2.0"
info:
  version: "1.0.0"
  title: Venue API
  description: API documentation for venue operations
tags:
  - name: Venues
    description: Operations related to venue data
paths:
  /api/venue/{city}/events:
    get:
      summary: Get all events in a specific city by venue
      tags:
        - Venues
      parameters:
        - in: path
          name: city
          required: true
          description: City of the venue
          schema:
            type: string
      responses:
        200:
          description: List of events in the specified city
        404:
          description: City not found or no events
  /api/venue:
    get:
      summary: Get all venues
      tags:
        - Venues
      responses:
        200:
          description: A list of all venues
    post:
      summary: Create a new venue
      tags:
        - Venues
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId:
                  type: string
                  description: ID of the associated event
                  example: "550e8400-e29b-41d4-a716-446655440000"
                name:
                  type: string
                  description: Name of the venue
                  example: "Central Park"
                address:
                  type: string
                  description: Address of the venue
                  example: "123 Main St"
                city:
                  type: string
                  description: City where the venue is located
                  example: "New York"
                capacity:
                  type: integer
                  description: Maximum capacity of the venue
                  example: 5000
                latitude:
                  type: number
                  format: float
                  description: Latitude coordinate of the venue
                  example: 40.785091
                longitude:
                  type: number
                  format: float
                  description: Longitude coordinate of the venue
                  example: -73.968285
      responses:
        201:
          description: Venue created successfully
        400:
          description: Invalid input
  /api/venue/{id}:
    get:
      summary: Get venue by ID
      tags:
        - Venues
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the venue
          schema:
            type: string
      responses:
        200:
          description: Venue details
        404:
          description: Venue not found
    put:
      summary: Update venue by ID
      tags:
        - Venues
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the venue to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the venue
                  example: "Central Park"
                address:
                  type: string
                  description: Address of the venue
                  example: "123 Main St"
                city:
                  type: string
                  description: City where the venue is located
                  example: "New York"
                capacity:
                  type: integer
                  description: Maximum capacity of the venue
                  example: 5000
                latitude:
                  type: number
                  format: float
                  description: Latitude coordinate of the venue
                  example: 40.785091
                longitude:
                  type: number
                  format: float
                  description: Longitude coordinate of the venue
                  example: -73.968285
      responses:
        200:
          description: Venue updated successfully
        400:
          description: Invalid input
        404:
          description: Venue not found
    delete:
      summary: Delete venue by ID
      tags:
        - Venues
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the venue to delete
          schema:
            type: string
      responses:
        200:
          description: Venue deleted successfully
        404:
          description: Venue not found
